'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    return queryInterface.bulkInsert('Users', [
    {
      userid:901,
      fname:"Andaman and Nicobar Islands",
      lname:null,
      userpwd:"123456",
      useremail:"an.india@helfinch.com",
      userpic:null,
      userstate:"Andaman and Nicobar Islands",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:902,
      fname:"Andhra Pradesh",
      lname:null,
      userpwd:"123456",
      useremail:"ap.india@helfinch.com",
      userpic:null,
      userstate:"Andhra Pradesh",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:903,
      fname:"Arunachal Pradesh",
      lname:null,
      userpwd:"123456",
      useremail:"ar.india@helfinch.com",
      userpic:null,
      userstate:"Arunachal Pradesh",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:904,
      fname:"Assam",
      lname:null,
      userpwd:"123456",
      useremail:"as.india@helfinch.com",
      userpic:null,
      userstate:"Assam",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:905,
      fname:"Bihar",
      lname:null,
      userpwd:"123456",
      useremail:"br.india@helfinch.com",
      userpic:null,
      userstate:"Bihar",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:906,
      fname:"Chhattisgarh",
      lname:null,
      userpwd:"123456",
      useremail:"cg.india@helfinch.com",
      userpic:null,
      userstate:"Chhattisgarh",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:907,
      fname:"Goa",
      lname:null,
      userpwd:"123456",
      useremail:"ga.india@helfinch.com",
      userpic:null,
      userstate:"Goa",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:908,
      fname:"Gujarat",
      lname:null,
      userpwd:"123456",
      useremail:"gj.india@helfinch.com",
      userpic:null,
      userstate:"Gujarat",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:909,
      fname:"Haryana",
      lname:null,
      userpwd:"123456",
      useremail:"hr.india@helfinch.com",
      userpic:null,
      userstate:"Haryana",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:910,
      fname:"Himachal Pradesh",
      lname:null,
      userpwd:"123456",
      useremail:"hp.india@helfinch.com",
      userpic:null,
      userstate:"Himachal Pradesh",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:911,
      fname:"Jammu and Kashmir",
      lname:null,
      userpwd:"123456",
      useremail:"jk.india@helfinch.com",
      userpic:null,
      userstate:"Jammu and Kashmir",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:912,
      fname:"Jharkhand",
      lname:null,
      userpwd:"123456",
      useremail:"jh.india@helfinch.com",
      userpic:null,
      userstate:"Jharkhand",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:913,
      fname:"Karnataka",
      lname:null,
      userpwd:"123456",
      useremail:"ka.india@helfinch.com",
      userpic:null,
      userstate:"Karnataka",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:914,
      fname:"Kerala",
      lname:null,
      userpwd:"123456",
      useremail:"kl.india@helfinch.com",
      userpic:null,
      userstate:"Kerala",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:915,
      fname:"Madhya Pradesh",
      lname:null,
      userpwd:"123456",
      useremail:"mp.india@helfinch.com",
      userpic:null,
      userstate:"Madhya Pradesh",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:916,
      fname:"Maharashtra",
      lname:null,
      userpwd:"123456",
      useremail:"mh.india@helfinch.com",
      userpic:null,
      userstate:"Maharashtra",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:917,
      fname:"Manipur",
      lname:null,
      userpwd:"123456",
      useremail:"mn.india@helfinch.com",
      userpic:null,
      userstate:"Manipur",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:918,
      fname:"Meghalaya",
      lname:null,
      userpwd:"123456",
      useremail:"ml.india@helfinch.com",
      userpic:null,
      userstate:"Meghalaya",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:919,
      fname:"Mizoram",
      lname:null,
      userpwd:"123456",
      useremail:"mz.india@helfinch.com",
      userpic:null,
      userstate:"Mizoram",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:920,
      fname:"Nagaland",
      lname:null,
      userpwd:"123456",
      useremail:"nl.india@helfinch.com",
      userpic:null,
      userstate:"Nagaland",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:921,
      fname:"Odisha",
      lname:null,
      userpwd:"123456",
      useremail:"od.india@helfinch.com",
      userpic:null,
      userstate:"Odisha",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:922,
      fname:"Punjab",
      lname:null,
      userpwd:"123456",
      useremail:"pb.india@helfinch.com",
      userpic:null,
      userstate:"Punjab",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:923,
      fname:"Rajasthan",
      lname:null,
      userpwd:"123456",
      useremail:"rj.india@helfinch.com",
      userpic:null,
      userstate:"Rajasthan",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:924,
      fname:"Sikkim",
      lname:null,
      userpwd:"123456",
      useremail:"sk.india@helfinch.com",
      userpic:null,
      userstate:"Sikkim",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:925,
      fname:"Tamil Nadu",
      lname:null,
      userpwd:"123456",
      useremail:"tn.india@helfinch.com",
      userpic:null,
      userstate:"Tamil Nadu",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:926,
      fname:"Tripura",
      lname:null,
      userpwd:"123456",
      useremail:"tr.india@helfinch.com",
      userpic:null,
      userstate:"Tripura",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:927,
      fname:"Uttar Pradesh",
      lname:null,
      userpwd:"123456",
      useremail:"up.india@helfinch.com",
      userpic:null,
      userstate:"Uttar Pradesh",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:928,
      fname:"Uttarakhanad",
      lname:null,
      userpwd:"123456",
      useremail:"uk.india@helfinch.com",
      userpic:null,
      userstate:"Uttarakhanad",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:929,
      fname:"West Bengal",
      lname:null,
      userpwd:"123456",
      useremail:"wb.india@helfinch.com",
      userpic:null,
      userstate:"West Bengal",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:930,
      fname:"Telangana",
      lname:null,
      userpwd:"123456",
      useremail:"ts.india@helfinch.com",
      userpic:null,
      userstate:"Telangana",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:931,
      fname:"Chandigarh",
      lname:null,
      userpwd:"123456",
      useremail:"ch.india@helfinch.com",
      userpic:null,
      userstate:"Chandigarh",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:932,
      fname:"Dadra and nagar Haveli",
      lname:null,
      userpwd:"123456",
      useremail:"dn.india@helfinch.com",
      userpic:null,
      userstate:"Dadra and nagar Haveli",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:933,
      fname:"Daman and Diu",
      lname:null,
      userpwd:"123456",
      useremail:"dd.india@helfinch.com",
      userpic:null,
      userstate:"Daman and Diu",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:934,
      fname:"Lakshadweep",
      lname:null,
      userpwd:"123456",
      useremail:"ld.india@helfinch.com",
      userpic:null,
      userstate:"Lakshadweep",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:935,
      fname:"Delhi",
      lname:null,
      userpwd:"123456",
      useremail:"dl.india@helfinch.com",
      userpic:null,
      userstate:"Delhi",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:936,
      fname:"Puducherry",
      lname:null,
      userpwd:"123456",
      useremail:"py.india@helfinch.com",
      userpic:null,
      userstate:"Puducherry",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:1000,
      fname:"Android",
      lname:"Developer",
      userpwd:"123456",
      useremail:"dev@helfinch.com",
      userpic:null,
      userstate:"Assam",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:58,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:1001,
      fname:"Satish",
      lname:"Krishnan",
      userpwd:"123456",
      useremail:"satish@helfinch.com",
      userpic:null,
      userstate:"Maharashtra",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:1002,
      fname:"Vishal",
      lname:"Sood",
      userpwd:"123456",
      useremail:"vishal.sood@helfinch.com",
      userpic:null,
      userstate:"Assam",
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:1003,
      fname:"Sanjay",
      lname:"Chandra",
      userpwd:"123456",
      useremail:"sanjay.chandra@helfinch.com",
      userpic:null,
      userstate:null,
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:1004,
      fname:"Sudip",
      lname:"Chowdhary",
      userpwd:"123456",
      useremail:"sudip.chowdhary@helfinch.com",
      userpic:null,
      userstate:null,
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:1005,
      fname:"Sujay",
      lname:"Jha",
      userpwd:"123456",
      useremail:"sujay.jha@helfinch.com",
      userpic:null,
      userstate:null,
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:1006,
      fname:"Wilson",
      lname:"Chacko",
      userpwd:"123456",
      useremail:"wilson@helfinch.com",
      userpic:null,
      userstate:null,
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:1007,
      fname:"Patricia",
      lname:"Ricken",
      userpwd:"123456",
      useremail:"patricia@helfinch.com",
      userpic:null,
      userstate:null,
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userid:1008,
      fname:"Chandan",
      lname:"Singh",
      userpwd:"123456",
      useremail:"chandan.singh@helfinch.com",
      userpic:null,
      userstate:null,
      usercity:null,
      userregion:null,
      mgruserid:null,
      usercategory:null,
      usertarget:null,
      usersales:null,
      userrank:null,
      userstatus:null,
      createdAt: new Date(),
      updatedAt: new Date()
    }
  ]);
  },

  async down (queryInterface, Sequelize) {
    return queryInterface.bulkDelete('Users', null, {});
  }
};